#!/bin/bash

while true; do
  ip="`ipconfig getifaddr en0`"
  wait_time=9

  if [[ $ip != 128* ]]; then
    `networksetup -setairportpower en0 off`
    `networksetup -setairportpower en0 on`
    sleep $wait_time
  else
    sleep 1
  fi
done
