#!/usr/bin/env bash

dir=`dirname "$0"`
# Source the interface file
. ${dir}"/interface"

# Time in seconds to wait after toggling
toggle_wait_time=9
regular_wait_time=1
# IP with which the current IP is compared
ip_compare=""

while true; do
  ip="`ipconfig getifaddr $interface`"

  if [[ $ip == $ip_compare ]]; then
    `networksetup -setairportpower $interface off`
    `networksetup -setairportpower $interface on`
    sleep $toggle_wait_time
  else
    sleep $regular_wait_time
  fi
done
